# Generated by Django 5.1.2 on 2024-10-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wb', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField()),
                ('feedbacks', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
