# Generated by Django 5.1.2 on 2024-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
