# Generated by Django 5.1.2 on 2024-11-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_items_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='main_market_id_d86e83_idx')],
            },
        ),
        migrations.AddField(
            model_name='items',
            name='mt_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marketplace'),
        ),
    ]
