# Generated by Django 5.1.2 on 2024-11-06 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_items_mt_place_items_mtplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='id_wb',
            new_name='id_item',
        ),
        migrations.AlterField(
            model_name='items',
            name='mtplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main.marketplace'),
        ),
    ]
