# Generated by Django 5.1.2 on 2024-11-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_id_wb_items_id_item_alter_items_mtplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='main.tagitem'),
        ),
    ]
