# Generated by Django 5.1.2 on 2024-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tagitem_items_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
