# Generated by Django 5.1.2 on 2024-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_items_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='content',
        ),
        migrations.AddField(
            model_name='items',
            name='feedbacks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='items',
            name='name_for_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Свое наименование'),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='items',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='items',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остатки на складе'),
        ),
    ]
