# Generated by Django 5.1.2 on 2024-12-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_items_content_items_feedbacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='mtplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.marketplace', verbose_name='Маркетплейс'),
        ),
    ]
