# Generated by Django 5.1.2 on 2024-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_itemschanges_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последняя стоимость'),
        ),
    ]
