# Generated by Django 5.1.2 on 2025-01-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_items_mtplace_alter_items_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemschanges',
            name='item_relations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_changes', to='main.items', verbose_name='Основной товар'),
        ),
    ]
